{% set name = "google-cloud-pubsublite" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-pubsublite-{{ version }}.tar.gz
  sha256: 923d956e8ff23b09d0ec930db5079e271c8d68e429e7a005feac623694c000b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - google-cloud-pubsub >=2.10.0,<3.0.0dev
    - grpcio >=1.38.1,<2.0.0dev
    - grpcio-status >=1.38.1,<2.0.0dev
    - overrides >=6.0.1,<7.0.0
    - google-api-core >=1.33.2,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-pubsublite
  summary: Google Cloud Pubsublite API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
